apiVersion: v1
kind: Service
metadata:
  name: ai-coach-service
  labels:
    app: ai-coach-service
spec:
  type: ClusterIP
  ports:
    - port: 3004
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ai-coach-service

