apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: found-fitness-app
  labels:
    app: auth-service
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "password"
  JWT_SECRET: "your_super_long_and_secure_base64_encoded_secret_key_here_at_least_256_bits_for_HS256"
