apiVersion: v1
kind: ConfigMap
metadata:
  name: challenge-service-config
  namespace: found-fitness-app
  labels:
    app: challenge-service
    component: config
data:
  config.env: |
    # Database
    DATABASE_URL="postgresql://postgres:ZPRiwCyhTO@my-postgresql.found-db:5432/fitness_tracker_challenges"
    
    # Service Configuration
    PORT=3002
    NODE_ENV=production
    
    # RabbitMQ
    RABBITMQ_URL="amqp://admin:admin@rabbitmq.rabbitmq.svc.cluster.local:5672"

