apiVersion: v1
kind: ConfigMap
metadata:
  name: challenge-service-config
  namespace: found-webapp
  labels:
    app: challenge-service
    component: config
data:
  config.env: |
    # Database
    DATABASE_URL="postgresql://postgres:password@challenge-db:5432/fitness_tracker_challenges"
    
    # Service Configuration
    PORT=3002
    NODE_ENV=production
    
    # RabbitMQ
    RABBITMQ_URL="amqp://guest:guest@rabbitmq:5672"

