apiVersion: v1
kind: Secret
metadata:
  name: leaderboard-service-secret
  namespace: found-fitness-app
  labels:
    app: leaderboard-service
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "ZPRiwCyhTO"

