apiVersion: v1
kind: ConfigMap
metadata:
  name: leaderboard-service-config
  labels:
    app: leaderboard-service
data:
  SERVER_PORT: "8080"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
