apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: found-fitness-app
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: WlBSaXdDeWhUTw==
  JWT_SECRET: eW91cl9zdXBlcl9sb25nX2FuZF9zZWN1cmVfYmFzZTY0X2VuY29kZWRfc2VjcmV0X2tleV9oZXJlX2F0X2xlYXN0XzI1Nl9iaXRzX2Zvcl9IUzI1Ng==
