apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: found-fitness-app
  labels:
    app: user-service
    component: config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://my-postgresql.found-db:5432/user_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
