apiVersion: v1
kind: ConfigMap
metadata:
  name: workout-service-config
  namespace: found-fitness-app
  labels:
    app: workout-service
    component: config
data:
  config.env: |
    # Database
    DATABASE_URL="postgresql://postgres:password@My-postgresql.found-db:5432/fitness_tracker_workouts"
    
    # Service Configuration
    PORT=3001
    NODE_ENV=production
    
    # RabbitMQ
    RABBITMQ_URL="amqp://guest:guest@rabbitmq:5672"

